<?php

namespace Omnipay\AuthorizeNet\Message;

use Omnipay\Common\Exception\InvalidRequestException;

/**
 * Authorize.Net SIM Complete Authorize Request
 */
class SIMCompleteAuthorizeRequest extends SIMAbstractRequest
{
    /**
     * Get the transaction ID passed in through the custom field.
     * This is used to look up the transaction in storage.
     */
    public function getTransactionId()
    {
        return $this->httpRequest->request->get(static::TRANSACTION_ID_PARAM);
    }

    public function getData()
    {
        // The hash sent in the callback from the Authorize.Net gateway.
        $hash_posted = $this->getPostedHash();

        // The transaction reference generated by the Authorize.Net gateway and sent in the callback.
        $posted_transaction_reference = $this->httpRequest->request->get('x_trans_id');

        // The amount that the callback has authorized.
        $posted_amount = $this->httpRequest->request->get('x_amount');

        // Calculate the hash locally, using the shared "hash secret" and login ID.
        $hash_calculated = $this->getHash($posted_transaction_reference, $posted_amount);

        if ($hash_posted !== $hash_calculated) {
            // If the hash is incorrect, then we can't trust the source nor anything sent.
            // Throwing exceptions here is probably a bad idea. We are trying to get the data,
            // and if it is invalid, then we need to be able to log that data for analysis.
            // Except we can't, baceuse the exception means we can't get to the data.
            // For now, this is consistent with other OmniPay gateway drivers.

            throw new InvalidRequestException('Incorrect hash');
        }

        // The hashes have passed, but the amount should also be validated against the
        // amount in the stored and retrieved transaction. If the application has the
        // ability to retrieve the transaction (using the transaction_id sent as a custom
        // form field, or perhaps in an otherwise unused field such as x_invoice_id.

        $amount = $this->getAmount();

        if (isset($amount) && $amount != $posted_amount) {
            // The amounts don't match. Someone may have been playing with the
            // transaction references.

            throw new InvalidRequestException('Incorrect amount');
        }

        return $this->httpRequest->request->all();
    }

    /**
     * CHECKME: should this be the transactionReference in the hash, not the transactionId?
     * The transaction reference and the amount are both sent by the remote gateway (x_trans_id
     * and x_amount) and it is those that should be checked against.
     * @param $transaction_reference
     * @param $amount
     * @param $httpRequest
     * @return string
     */
    public function getHash($transaction_reference, $amount)
    {
        if ($this->getSignatureKey()) {
            return $this->getSha512Hash();
        } else {
            return $this->getMd5Hash($transaction_reference, $amount);
        }
    }

    /**
     * Generate md5 hash.
     *
     * @param $transaction_reference
     * @param $amount
     * @return string
     */
    public function getMd5Hash($transaction_reference, $amount)
    {
        $key = array(
            $this->getHashSecret(),
            $this->getApiLoginId(),
            $transaction_reference,
            $amount,
        );

        return md5(implode('', $key));
    }

    /**
     * Generate sha512 hash.
     * Required fields are provided in Table 18 in
     * https://www.authorize.net/content/dam/authorize/documents/SIM_guide.pdf#page=73
     * @param $httpRequest
     * @return string|null
     */
    public function getSha512Hash()
    {
        $signatureKey = $this->getSignatureKey();
        $httpRequest = $this->httpRequest->request;

        if (empty($signatureKey)) {
            return null;
        }

        $hashData = implode('^', [
            $httpRequest->get('x_trans_id'),
            $httpRequest->get('x_test_request'),
            $httpRequest->get('x_response_code'),
            $httpRequest->get('x_auth_code'),
            $httpRequest->get('x_cvv2_resp_code'),
            $httpRequest->get('x_cavv_response'),
            $httpRequest->get('x_avs_code'),
            $httpRequest->get('x_method'),
            $httpRequest->get('x_account_number'),
            $httpRequest->get('x_amount'),
            $httpRequest->get('x_company'),
            $httpRequest->get('x_first_name'),
            $httpRequest->get('x_last_name'),
            $httpRequest->get('x_address'),
            $httpRequest->get('x_city'),
            $httpRequest->get('x_state'),
            $httpRequest->get('x_zip'),
            $httpRequest->get('x_country'),
            $httpRequest->get('x_phone'),
            $httpRequest->get('x_fax'),
            $httpRequest->get('x_email'),
            $httpRequest->get('x_ship_to_company'),
            $httpRequest->get('x_ship_to_first_name'),
            $httpRequest->get('x_ship_to_last_name'),
            $httpRequest->get('x_ship_to_address'),
            $httpRequest->get('x_ship_to_city'),
            $httpRequest->get('x_ship_to_state'),
            $httpRequest->get('x_ship_to_zip'),
            $httpRequest->get('x_ship_to_country'),
            $httpRequest->get('x_invoice_num'),
        ]);
        $hash = hash_hmac('sha512', '^' . $hashData . '^', hex2bin($signatureKey));
        $hash = strtoupper($hash);

        return $hash;
    }

    /**
     * Get posted hash from the callback from the Authorize.Net gateway.
     *
     * @return string|null
     */
    public function getPostedHash()
    {
        if ($signatureKey = $this->getSignatureKey()) {
            return strtoupper($this->httpRequest->request->get('x_SHA2_Hash'));
        }

        return strtolower($this->httpRequest->request->get('x_MD5_Hash'));
    }

    public function sendData($data)
    {
        return $this->response = new SIMCompleteAuthorizeResponse($this, $data);
    }
}
